### PR TITLE
chore: rollback cassandra to 3.11.16

### PR DESCRIPTION
**Pull request by lzyxx77**
## Purpose of the PR

This pull request reverts the changes introduced in PR #2300  , which upgraded Cassandra from version 3.11.12 to 4.0.10. The upgrade caused compatibility issues that were not anticipated, and as a result, we are reverting back to 3.11.16 version to maintain stability and functionality.

## Main Changes

- Reverting the Cassandra version from 4.0.10 to 3.11.16 to address compatibility issues.
- Ensuring stability and functionality are maintained during this transition.

### Note Regarding 3rd Party Error
Users experiencing the error reported by 3rd party (GHSA-m9p2-j4hg-g373) should note that we have upgraded to Cassandra version 3.11.16. 

image

This issue may be related to Cassandra 3, and any resolution might be addressed when upgrading to Cassandra 4. As this is not within our control, we recommend monitoring Cassandra updates for a potential fix.

屏幕截图 2023-12-04 214128

## Verifying these changes

- [ ] Trivial rework / code cleanup without any test coverage. (No Need)
- [ ] Already covered by existing tests, such as *(please modify tests here)*.
- [ ] Need tests and can be verified as follows:
    - xxx

## Does this PR potentially affect the following parts?

- [ ]  Nope
- [x]  Dependencies (add/update license info) 
- [ ]  Modify configurations
- [ ]  The public API
- [ ]  Other affects (typed here)

## Documentation Status

- [ ]  `Doc - TODO` 
- [ ]  `Doc - Done` 
- [x]  `Doc - No Need`

### CODE REVIEW

**Comment by aroundabout** [comment]
https://github.com/apache/incubator-hugegraph/blob/062bb3da5ffec6ddaebf14768d4c11ab8aaaf6b8/hugegraph-server/hugegraph-dist/docker/example/docker-compose-cassandra.yml#L42

There is a related file here, we use cassandra:4 in docker-compose. If we rollback cassandra, maybe we should change the version here

**Comment by imbajin** [comment]
> https://github.com/apache/incubator-hugegraph/blob/062bb3da5ffec6ddaebf14768d4c11ab8aaaf6b8/hugegraph-server/hugegraph-dist/docker/example/docker-compose-cassandra.yml#L42
> 
> There is a related file here, we use cassandra:4 in docker-compose. If we rollback cassandra, maybe we should change the version here.
> I think we only need to change it to `cassandra:3.11`.

thanks for the reminder，seems we do need it

**Comment by lzyxx77** [comment]
> https://github.com/apache/incubator-hugegraph/blob/062bb3da5ffec6ddaebf14768d4c11ab8aaaf6b8/hugegraph-server/hugegraph-dist/docker/example/docker-compose-cassandra.yml#L42
> 
> There is a related file here, we use cassandra:4 in docker-compose. If we rollback cassandra, maybe we should change the version here. I think we only need to change it to `cassandra:3.11`.

thank you! I will fix it

**Review by simon824 — APPROVED** [review]

**Review by imbajin — CHANGES_REQUESTED** [review]
wait u to ensure the https://github.com/apache/incubator-hugegraph/pull/2365 CI passed 


Update in 12.6: Suspend this PR due to #2365 CI passed (we need dig out the reason maybe?)

**Pull request closed without merging**
