### PR TITLE
chore(apache): add apache license checker for CI

### PR DESCRIPTION
**Pull request by dongzl**

### CODE REVIEW

**Comment by imbajin** [comment]
thanks for your contribution

wonder to know the differ with our current CI （like in toolchain @simon824 ） ，use mvn mat：check to check the license

and we dont need to add license header in github's file because they will not package into source file

**Comment by dongzl** [comment]
> toolchain



> thanks for your contribution
> 
> wonder to know the differ with our current CI （like in toolchain @simon824 ） ，it use mvn mat：check to check the license.
> 
> and we don't need to add license header in github's file because they won't be packaged into source file. (refer pom.xml in root)



> thanks for your contribution
> 
> wonder to know the differ with our current CI （like in toolchain @simon824 ） ，it use mvn mat：check to check the license.
> 
> and we don't need to add license header in github's file because they won't be packaged into source file. (refer pom.xml in root)

Thanks for your reply.

I am sorry, I don't understand the `toolchain` and how to use it.  Do you mean `apache-rat-plugin`?

This PR `License checker` can check the file license automatically when someone submit new PR.

yes, we can ignore `github` package.

**Comment by imbajin** [comment]
like this pr in toolchain（repo）

https://github.com/apache/incubator-hugegraph-toolchain/pull/352

it also check the license in CI

**Comment by dongzl** [comment]
> 

OK, I known, thanks.

`License checker(use [apache/skywalking-eyes](https://github.com/apache/skywalking-eyes))` maybe more powerful.
It can check license, and add file license and replace file license in batches.

But the common scenes is check file license.  we have these capability, I will close these this PR, thanks.

**Comment by imbajin** [comment]
seems it's nice if it could add the license automatically

@JackyYangPassion could u try or compare it?

**Comment by dongzl** [comment]
> > add file license and replace file license in batches
> 
> hi @dongzl , `add file license in batches` does it means can automatic generate thrid-party dependancy LICENSE file ? (like [these license files](https://github.com/apache/skywalking-eyes/blob/main/dist/licenses/license-cloud.google.com-go-bigquery.txt) )

Hi @simon824, It can add license header in batches when the source files doesn't have license header.

**Comment by dongzl** [comment]
> seems it's nice if it could add the license automatically
> 
> @JackyYangPassion could u try or compare it?
> 
> and we do have the wechat group, I have send u a email including the ID already~

Thanks,  email is `598363102@qq.com` or mobile(wechat ID) is `13436670847`.

**Review by zyxxoo — APPROVED** [review]

**Comment by imbajin** [comment]
in current case, how dose it add the lin'celicense automatically?

image

**Comment by imbajin** [comment]
@dongzl could refer the pom's lines to finish this PR
https://github.com/apache/incubator-hugegraph/blob/7acd496e0b6356e326553dd3b126b15ab1cd766c/pom.xml#L394

**Comment by dongzl** [comment]
close by #2034

**Pull request closed without merging**
