### PR TITLE
doc: modify ASF and remove meaningless CLA

### PR DESCRIPTION
**Pull request by KeeProMise**
1.Discussion is also split into discussion_status and discussion_comment, the former sends dev and the latter sends issues, so as to avoid the disturbance of a dev email for each comment and affect the effectiveness of everyone's subscription.
2.There is an obsolete and unnecessary CLA signature in our contribution doc, just remove it

### CODE REVIEW

**Review by imbajin — APPROVED** [review]
LGTM

**Review by imbajin — CHANGES_REQUESTED** [review]
sync 3rd party doc section from website

**Comment by KeeProMise** [comment]
> sync 3rd party doc section from website

I have submitted the newly added documents to my warehouse yesterday, why is the pr not updated here?
https://github.com/KeeProMise/incubator-hugegraph/tree/ASF_CLA

**Comment by KeeProMise** [comment]
> sync 3rd party doc section from website

https://github.com/KeeProMise/incubator-hugegraph/commit/c7a869adf3adc9bcfc826cacb6278e9245822e11

**Comment by imbajin** [comment]
> > sync 3rd party doc section from website
> 
> I have submitted the newly added documents to my warehouse yesterday, why is the pr not updated here?
> https://github.com/KeeProMise/incubator-hugegraph/tree/ASF_CLA

try to submit an empty commit？
（or ask gpt）

**Comment by KeeProMise** [comment]
> > > sync 3rd party doc section from website
> > 
> > 
> > I have submitted the newly added documents to my warehouse yesterday, why is the pr not updated here?
> > https://github.com/KeeProMise/incubator-hugegraph/tree/ASF_CLA
> 
> try to submit an empty commit？ （or ask gpt）

should be ok

**Review by imbajin — APPROVED** [review]

**Review by javeme — APPROVED** [review]
LGTM

**Pull request merged**
