### PR TITLE
flatmap

### PR DESCRIPTION
**Pull request by tzphh**
## Purpose of the PR

- close #xxx  

## Verifying these changes

- [ ] Trivial rework / code cleanup without any test coverage. (No Need)
- [ ] Already covered by existing tests, such as *(please modify tests here)*.
- [ ] Need tests and can be verified as follows:
    - xxx

## Does this PR potentially affect the following parts?

- [ ]  Nope
- [ ]  Dependencies (add/update license info) 
- [ ]  Modify configurations
- [ ]  The public API
- [ ]  Other affects (typed here)

## Documentation Status

- [ ]  `Doc - TODO` 
- [ ]  `Doc - Done` 
- [ ]  `Doc - No Need`

### CODE REVIEW

**Comment by imbajin** [comment]
Hi, please add more context for this PR? Thanks a lot~

**Comment by javeme** [comment]
Is it still in progress?

**Comment by javeme** [comment]
Is it still in progress?

**Comment by imbajin** [comment]
close for outdated & no response for a long time

**Pull request closed without merging**
