### PR TITLE
fix(server): unify the license headers

### PR DESCRIPTION
**Pull request by msgui**
## Purpose of the PR

- subtask of #2435

## Verifying these changes

- [ ] Trivial rework / code cleanup without any test coverage. (No Need)
- [ ] Already covered by existing tests, such as *(please modify tests here)*.
- [ ] Need tests and can be verified as follows:
    - xxx

## Does this PR potentially affect the following parts?

- [x]  Nope
- [ ]  Dependencies (add/update license info) 
- [ ]  Modify configurations
- [ ]  The public API
- [ ]  Other affects (typed here)

## Documentation Status

- [ ]  `Doc - TODO` 
- [ ]  `Doc - Done` 
- [x]  `Doc - No Need`

### CODE REVIEW

**Review by imbajin — COMMENTED** [review]
fine, wonder to know all the files header   are updated?

**Comment by msgui** [comment]
> fine, wonder to know all the files header are updated?

This PR solely updates the license header in `hg-server/hg-api`.

**Comment by imbajin** [comment]
> > fine, wonder to know all the files header are updated?
> 
> This PR solely updates the license header in `hg-server/hg-api`.

Get it, license header could update together (due to it is almost a completely repetitive task, just take a few samples for inspection and confirmation)

**Comment by VGalaxies** [comment]
@msgui I noticed that some configuration files, such as `hugegraph-server/hugegraph-test/src/main/resources/hugegraph.properties`, do not have corresponding modified license headers. Is this expected?

**Comment by msgui** [comment]
> correct License hg-server

thanks for the reminder

**Review by VGalaxies — CHANGES_REQUESTED** [review]
Two issues:
1. It seems reasonable to consider updating the license header for the entire repository, not just under `hugegraph-server`.
2. For the license headers only under `hugegraph-server`, there still seem to be some missed files. I have conducted a preliminary count:
image
(expected: 791, actual: 783)

**Comment by VGalaxies** [comment]
Also, these extra blank lines here can be removed, it seems?
image
(compared to https://github.com/apache/incubator-hugegraph/wiki/HugeGraph-Code-Style-Guide)

**Comment by msgui** [comment]
> PTAL~
> 
> 1. It seems reasonable to consider updating the license header for the entire repository, not just under `hugegraph-server`.
> 2. For the license headers only under `hugegraph-server`, there still seem to be some missed files. I have conducted a preliminary count (just a reminder):
>    image
>    (expected: 791, actual: 783)


Thanks for the heads up. Confirm that the license header format in the remaining eight files is correct or that no license header exists.

**Review by VGalaxies — DISMISSED** [review]
Great work! I have performed verification locally following the steps in [Project Migration/Package Name Change + IDEA Configuration Instructions (Complete Version)](https://hugegraph.feishu.cn/wiki/C3U3wWOGSi5z3jkTRpIc5nwdnrb), and it meets expectations.

@msgui Consider supplementing the **detailed** steps for updating copyright to the above document, explaining how to configure IDEA from scratch and how to update copyright with a single click (Because I encountered some unclear points during the configuration process, such as how to match the files that need updating, the relevant content in the above document is somewhat scattered. It might be beneficial to consolidate it together)

image

**Comment by VGalaxies** [comment]
@imbajin could also check again~

Additionally, I believe that performing the license header check in the current CI (licence-checker.yml) seems somewhat delayed. It might be worth considering moving it to the **verify** stage. This way, developers can discover related errors earlier during local builds.

**Comment by imbajin** [comment]
> @imbajin could also check again~
> 
> Additionally, I believe that performing the license header check in the current CI (licence-checker.yml) seems somewhat delayed. It might be worth considering moving it to the **verify** stage. This way, developers can discover related errors earlier during local builds.

Good suggestion, could mark it as a TODO (enhance our CI to check/validate style problems)

**Comment by liuxiaocs7** [comment]
This tool [hawkeye](https://github.com/korandoru/hawkeye) may help license header check and format?

**Comment by imbajin** [comment]
TODOs:
- [ ] keep the LICENSE header from refer code (revert/exclude it by reg?)
- [ ] rearrange the commit range
- [ ] keep the `dist/*/bin/*.properties` (user config files) clean (no need add header here)
- [ ]

**Review by imbajin — COMMENTED** [review]
TODOs:
- [x] keep the LICENSE header from refer code (revert/exclude it by reg?)
- [ ] rearrange the commit range
- [ ] keep the `dist/*/bin/*.properties` (user config files) clean (no need to add header here)
- [ ] remove the header in `org.apache.tinkerpop.gremlin.server.OpProcessor` or `GremlinPlugin` (pure text file)

**Review by VGalaxies — CHANGES_REQUESTED** [review]
image

It seems that some files license headers are inconsistent with those in https://github.com/apache/incubator-hugegraph/wiki/HugeGraph-Code-Style-Guide.

> TODOs:
> - [ ] keep the LICENSE header from refer code (revert/exclude it by reg?)
> - [ ] rearrange the commit range
> - [ ] keep the `dist/*/bin/*.properties` (user config files) clean (no need to add header here)
> - [ ] remove the header in `org.apache.tinkerpop.gremlin.server.OpProcessor` or `GremlinPlugin` (pure text file)

Also, do the TODOs here need to be addressed in this PR? @imbajin

**Review by imbajin — DISMISSED** [review]
Almost have checked all the files already (Also finished all the TODOS now)

**Review by VGalaxies — APPROVED** [review]
LGTM~

**Review by imbajin — APPROVED** [review]

**Review by imbajin — APPROVED** [review]

**Comment by VGalaxies** [comment]
> * [x]  keep the `dist/*/bin/*.properties` (user config files) clean (no need to add header here)

@imbajin Is it only for cleaning the license header in **properties** files in user configuration files here? I found that some other user configuration files have license headers.

image

Also, do **properties** files in the `conf-raft*` directory need to have their license headers cleaned?

image

**Comment by imbajin** [comment]
> > * [x]   keep the `dist/*/bin/*.properties` (user config files) clean (no need to add header here)
> 
> @imbajin Is it only for cleaning the license header in **properties** files in user configuration files here? I found that some other user configuration files have license headers.
> 
> image
> 
> Also, do **properties** files in the `conf-raft*` directory need to have their license headers cleaned?
> 
> image

@VGalaxies 
The current judgment points are:
1. If a configuration file is not **frequently used/modified** by **users**, following ASF's suggestion may be better to add a file header to reduce disputes
2. In HG, considering that there are already many configuration files and the content is relatively long, the commonly used configurations by users are not separately added to avoid affecting the **user experience** 
3. (like point 1) Configuration files from testing/and other modules could also add headers (although not required)

**Pull request merged**
