### PR TITLE
refact: adjust project structure for merge PD & Store[Breaking Change]

### PR DESCRIPTION
**Pull request by VGalaxies**
## Purpose of the PR

Subtask of #2265.

Adjust the project structure of this repository to include three sub-modules: hugegraph-server, hugegraph-pd, hugegraph-store at the root level.

## Main Changes

Roll back to the moment when https://github.com/apache/incubator-hugegraph/pull/2266 was merged on `pd-store` and incorporate the latest changes in `master`.

For more detailed information, please refer to https://github.com/apache/incubator-hugegraph/pull/2266#issue-1834369489.

**TODO:**

- [ ] check `pom.xml`
- [x] pass required CI
- [x] core (common) version

## Verifying these changes

- [ ] Trivial rework / code cleanup without any test coverage. (No Need)
- [ ] Already covered by existing tests, such as *(please modify tests here)*.
- [x] Need tests and can be verified as follows:
    - CI

## Does this PR potentially affect the following parts?

- [ ]  Nope
- [ ]  Dependencies (add/update license info) 
- [ ]  Modify configurations
- [ ]  The public API
- [x]  Other affects (breaking changes)

## Documentation Status

- [x]  `Doc - TODO` 
- [ ]  `Doc - Done` 
- [ ]  `Doc - No Need`

### CODE REVIEW

**Comment by imbajin** [comment]
seems we shouldn't import guava separatly, it should be imported & define version by `hugegrpah-common` (could check the import, or just remove it if we already import common?)

image

**Comment by VGalaxies** [comment]
> seems we shouldn't import guava separatly, it should be imported & define version by `hugegrpah-common` (could check the import, or just remove it if we already import common?)
> 
> image

already imported in `hugegraph-common` (with version `30.0-jre`), so removed

**Comment by imbajin** [comment]
Also. the `grpc` dependencies should be imported from `hugegraph-commons-rpc`? (could also check & replace it) to solve the 3rd-party check

**Comment by VGalaxies** [comment]
> Similarly, the `grpc` dependencies should be imported from `hugegraph-commons-rpc`? (could also check & replace it) to solve the 3rd-party check

found in `org.apache.hugegraph:hugegraph-rpc:jar:1.0.1` - `com.alipay.sofa:sofa-rpc-all:jar:5.7.6` - `io.grpc:grpc-protobuf:jar:1.28.0` (with lower version compared to `hugegraph-server`)

**Comment by imbajin** [comment]
LGTM, merge it after #2337

**Review by zyxxoo — DISMISSED** [review]

**Review by imbajin — APPROVED** [review]

**Review by zyxxoo — APPROVED** [review]

**Pull request merged**
