### PR TITLE
fix(core): support order by id 

### PR DESCRIPTION
**Pull request by liuxiaocs7**
## Purpose of the PR

- close: #1965  

## Verifying these changes

- This change is a trivial rework / code cleanup without any test coverage.

*(or)*

- This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

- This change added tests and can be verified as follows:

    - *Add UT.*

## Does this PR potentially affect the following parts?

- [ ]  Nope
- [ ]  Dependencies (add/update license info) 
- [X]  Modify configurations
- [X]  The public API
- [ ]  Other affects (typed here)

## Documentation Status

- [ ]  `Doc - TODO` 
- [ ]  `Doc - Done` 
- [X]  `Doc - NO Need`

### CODE REVIEW

**Review by javeme — DISMISSED** [review]
LGTM

**Comment by javeme** [comment]
please note ci error:
```
Caused by: com.mysql.cj.exceptions.WrongArgumentException:
The connection property 'useSSL' acceptable values are: 'TRUE', 'FALSE', 'YES' or 'NO'. The value 'disable' is not acceptable.
```

prefer to update `ssl_mode` in a separate PR.

**Comment by liuxiaocs7** [comment]
> please note ci error:
> 
> ```js
> Caused by: com.mysql.cj.exceptions.WrongArgumentException:
> The connection property 'useSSL' acceptable values are: 'TRUE', 'FALSE', 'YES' or 'NO'.
>  The value 'disable' is not acceptable.
> ```
> 
> prefer to update `ssl_mode` in a separate PR.

got it, thanks!

**Review by javeme — APPROVED** [review]
LGTM

**Review by imbajin — APPROVED** [review]

**Pull request merged**
